language: node_js
node_js:
  - 0.10

services: mongodb

before_install:
 - wget -P ../ https://download.srcclr.com/console/srcclr-console-latest.zip
 - unzip ../srcclr-console-latest.izip -d ../ && rm ../srcclr-console-latest.zip && mv ../srcclr-console-* ../srcclr

script:
 - echo -e '\ne4fbe422-e8fb-4d68-8d2d-714667cf59c6\n\n\n\nquit' | ../srcclr/srcclr
 - ../srcclr/srcclr -e "scan --path $PWD"
